### ISSUE TITLE
ZZZ seemingly unmapped

### ISSUE THREAD

**Issue by Kamii-Sam** [Escartem/AnimeWwise#10]
![image](https://github.com/user-attachments/assets/2c66924e-8038-4b44-b551-74340d39f36e)

This is the result I get. It should be noted that ZZZ was updated to 1.1, would that break the mapping?

**Comment by Escartem** [comment]
zzz update should not break the mapping, and it's only made for voicelines not sfx / music as far as i know, i see you closed the issue so is it good now ?
