### ISSUE TITLE
Genshin Impact cannot be mapped.

### ISSUE THREAD

**Issue by AesoVita** [Escartem/AnimeWwise#12]
The version of Genshin Impact is 5.0. After following the tutorial, it shows that all media files are unmapped and the sound effects or voice files cannot be found. Thank you for your help.
![a07559ee6b5d74ae3d10187e9dbe6bc](https://github.com/user-attachments/assets/2a396414-cf9d-4ca8-816b-422875a88feb)

**Comment by AesoVita** [comment]
Furthermore, I just discovered that Star Rail cannot be unpacked either. All the unpacked files are not correctly named. The version of Star Rail is 2.4, and I couldn’t find the dedicated voice folder for Star Rail. How do you unpack Star Rail? Thank you very much

**Comment by Escartem** [comment]
If you look at maps/index.json, you can see the game version of each map (also displayed in the console when you load the files)

Genshin is still at 4.8 and star rail at 2.2. Genshin will be updated soon and for star rail some rework is required for it to work better

**Comment by AesoVita** [comment]
Thank you very much for your reply. I have successfully unpacked the voice files for Genshin Impact and ZZZ, which has been of great help to me. However, I still haven't managed to unpack the voice files for Star Rail. Thank you for continuing to maintain the project, and I look forward to the day when I can unpack the Star Rail files. By the way, since it's possible to unpack voice files, is there also a possibility to unpack sound effect files? This would be even more important to me. I look forward to your reply.

**Comment by Escartem** [comment]
As of right now only voicelines are supported, I may do some tests for sfx but I can't guarantee anything

**Comment by Escartem** [comment]
The mapping for Genshin is now updated, I tested on the 5.0 update, there are still unmapped files but overall looks fine

**Comment by AesoVita** [comment]
Thank you very much for your reply. I will continue to follow your project, and it would be great if partial mapping of SFX is possible. Looking forward to your next update.
