### ISSUE TITLE
"invalid continuation byte" error while extracting

### ISSUE THREAD

**Issue by chemistzombie** [Escartem/AnimeWwise#3]
Attempting to extract most PCK files simply results in a bunch of errors.

```
65 file(s) to extract
--- Banks0.pck (1/65) ---
[1/5] Extracting ◠An error occured while processing this file ! Skipping to the next one, details of the error bellow :
Line 84, 'utf-8' codec can't decode byte 0xc3 in position 8: invalid continuation byte
--- Banks1.pck (2/65) ---
An error occured while processing this file ! Skipping to the next one, details of the error bellow :
Line 73, [WinError 32] The process cannot access the file because it is being used by another process: 'temp\\Banks0.pck'
--- Banks10.pck (3/65) ---
An error occured while processing this file ! Skipping to the next one, details of the error bellow :
Line 73, [WinError 32] The process cannot access the file because it is being used by another process: 'temp\\Banks0.pck'

(repeated lines of the same WinError 32 thing)

--- Streamed9.pck (65/65) ---
An error occured while processing this file ! Skipping to the next one, details of the error bellow :
Line 73, [WinError 32] The process cannot access the file because it is being used by another process: 'temp\\Banks0.pck'
Traceback (most recent call last):
  File "C:\Users\test\Downloads\AnimeWwise-master\extract.py", line 333, in <module>
    main()
  File "C:\Users\test\Downloads\AnimeWwise-master\extract.py", line 329, in main
    shutil.rmtree("temp")
  File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 749, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 619, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 617, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'temp\\Banks0.pck'
```

The failure to decode the first file seems to be the root cause, because attempting to decode the US English audio files from the mobile version succeeds with the first found file and cleaned up the temp folder properly, but immediately fails for the second one with the same error:

```
122 file(s) to extract
--- 1001.pck (1/122) ---
[1/5] Extracting
[2/5] Converting to wav  |⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿| 100.0% - 0s left
[3/5] Converting to mp3  |⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿| 100.0% - 0s left
[4/5] Mapping names
[5/5] Cleaning up
--- 1002.pck (2/122) ---
[1/5] Extracting ◠An error occured while processing this file ! Skipping to the next one, details of the error bellow :
Line 84, 'utf-8' codec can't decode byte 0x8f in position 12: invalid start byte
--- 1003.pck (3/122) ---
An error occured while processing this file ! Skipping to the next one, details of the error bellow :
Line 73, [WinError 32] The process cannot access the file because it is being used by another process: 'temp\\1002.pck'
--- 1004.pck (4/122) ---
An error occured while processing this file ! Skipping to the next one, details of the error bellow :
Line 73, [WinError 32] The process cannot access the file because it is being used by another process: 'temp\\1002.pck'

(repeated lines of the same WinError 32)

--- VO_4.1_0.pck (122/122) ---
An error occured while processing this file ! Skipping to the next one, details of the error bellow :
Line 73, [WinError 32] The process cannot access the file because it is being used by another process: 'temp\\1002.pck'
Traceback (most recent call last):
  File "C:\Users\test\Downloads\AnimeWwise-master\extract.py", line 333, in <module>
    main()
  File "C:\Users\test\Downloads\AnimeWwise-master\extract.py", line 329, in main
    shutil.rmtree("temp")
  File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 749, in rmtree
[1/5] Extracting ◠    return _rmtree_unsafe(path, onerror)
  File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 619, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 617, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'temp\\1002.pck'
```

I'm using Python 3.10.6 and have followed the instructions including installing the requirements.

**Comment by Escartem** [comment]
Very weird, the error about the file being not accessible is because the byte error happens at extraction so the current file is never released from memory. But apart from that, there's something it can't read. Is Banks0.pck from genshin or another game ?

**Comment by chemistzombie** [comment]
It's from Genshin. [Here](https://mega.nz/folder/sk122a5T#2myYfvgcQ7EnS9dAPW4iYg) are the files I was trying to use that results in the error.

**Comment by Escartem** [comment]
okay thanks, i'll look into this as soon as I can, I'm assuming a change was made in 4.2 since I tested this tool with 4.1 audio files

**Comment by Escartem** [comment]
hi again, I just pushed a few fixes to the tool, try downloading the updated version and extract your files again, it should work now, keep me updated if something is still broken :)

**Comment by Miltropolitz** [comment]
ok,  I think I'm experiencing a similar error atm, even with the most up-to-date tool. I tried changing from SSD to USB, and cmd in both regular and admin modes, but i still get permission errors. :(

**Comment by Escartem** [comment]
@Miltropolitz could you please provide the file(s) you're trying to extract ? I'll try on my side to see if it works

**Comment by chemistzombie** [comment]
> hi again, I just pushed a few fixes to the tool, try downloading the updated version and extract your files again, it should work now, keep me updated if something is still broken :)

Alright, it seems like it's finally working when I extract the English VO PCK files this time and assigned the proper file names for those that are mapped, though one potential issue is that it fails when trying to map the file names on the Banks0.pck file that I shared on Mega in my previous comment, with the error message being:
`An error occured while processing this file ! Skipping to the next one, details of the error bellow :
Line 298, [Errno 2] No such file or directory: 'C:\\Users\\test\\Downloads\\AnimeWwise-master\\AnimeWwise-master\\temp/mp3/100514812.mp3'`

I know this is some sort of an edge case as the Banks files only contain sound effects and are almost certainly unmapped, but it might be worth fixing just in case this happens when extracting files that are not from Genshin. Other than that though, extracting the VO files work okay, so I'm glad that's resolved.

**Comment by Escartem** [comment]
> I know this is some sort of an edge case as the Banks files only contain sound effects and are almost certainly unmapped, but it might be worth fixing just in case this happens when extracting files that are not from Genshin. Other than that though, extracting the VO files work okay, so I'm glad that's resolved.

After some testing the error was not caused by mapping, but way earlier in the program when extracting audio, I pushed another fix and now the error should be resolved

**Comment by Escartem** [comment]
It's been 2 weeks so I'm assuming it's fixed, feel free to comment again if it still doesn't work
