### ISSUE TITLE
how to get .pck.hdiff file?

### ISSUE THREAD

**Issue by MostW** [Escartem/AnimeWwise#4]
Excuse me, in the third step, I search .pck.hdiff on network and  local asset, but can not find how to get it. Can you provider some tips, thank you very much.

**Comment by Escartem** [comment]
.pck files are the audio files in the game, when there is an update, to save up size there are .pck.hdiff in the zip it downloads which only contains new / changed stuff. So you'll only see these in the game patches files not in the game itself

**Comment by MostW** [comment]
thanks
